from sqlalchemy import String, Text, Integer, ForeignKey, JSON, DateTime, Index, Computed, text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID, TSVECTOR
from sqlalchemy import func
from pgvector.sqlalchemy import Vector
import uuid
from app.models.base import Base


class KnowledgeDocument(Base):
    __tablename__ = "knowledge_documents"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    source_url: Mapped[str | None] = mapped_column(Text)
    source_type: Mapped[str] = mapped_column(String(50), default="documentation")  # documentation | paper | course
    author: Mapped[str | None] = mapped_column(String(255))
    version: Mapped[str | None] = mapped_column(String(50))
    ingested_at: Mapped[DateTime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    # Set for ingested lessons so retrieval can boost the student's current lesson.
    content_ref_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("content_refs.id", ondelete="SET NULL"), nullable=True
    )

    chunks: Mapped[list["DocumentChunk"]] = relationship("DocumentChunk", back_populates="document")

    __table_args__ = (
        Index("ix_knowledge_documents_content_ref_id", "content_ref_id"),
        # source_url is a document's identity for idempotent re-ingestion.
        Index("uq_knowledge_documents_source_url", "source_url", unique=True,
              postgresql_where=text("source_url IS NOT NULL")),
    )


class DocumentChunk(Base):
    __tablename__ = "document_chunks"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("knowledge_documents.id", ondelete="CASCADE"), index=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    token_count: Mapped[int | None] = mapped_column(Integer)
    metadata_: Mapped[dict] = mapped_column("metadata", JSON, default=dict)
    # Generated by Postgres for full-text (sparse) retrieval; never written by the app.
    content_tsv: Mapped[str | None] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', content)", persisted=True)
    )

    document: Mapped["KnowledgeDocument"] = relationship("KnowledgeDocument", back_populates="chunks")
    embedding: Mapped["KnowledgeEmbedding"] = relationship("KnowledgeEmbedding", back_populates="chunk", uselist=False)

    __table_args__ = (
        Index("ix_document_chunks_content_tsv", "content_tsv", postgresql_using="gin"),
    )


class KnowledgeEmbedding(Base):
    __tablename__ = "knowledge_embeddings"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    chunk_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("document_chunks.id", ondelete="CASCADE"), unique=True)
    embedding: Mapped[Vector] = mapped_column(Vector(384), nullable=False)  # all-MiniLM-L6-v2 dim=384

    chunk: Mapped["DocumentChunk"] = relationship("DocumentChunk", back_populates="embedding")

    # HNSW needs no training step, so it stays correct on an empty or growing table.
    __table_args__ = (
        Index("ix_knowledge_embeddings_hnsw", "embedding", postgresql_using="hnsw",
              postgresql_with={"m": 16, "ef_construction": 64},
              postgresql_ops={"embedding": "vector_cosine_ops"}),
    )
